config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy], path_names: { new: '' }
  resources :posts do
    get 'search', on: :collection
  end
  
  root to: 'static_pages#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :name, :body, presence: true
  validates :name, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_title_and_body, against: [:title, :body]
  default_scope { order(created_at: :desc) }
  
  belongs_to :user
  has_many :comments
  validates :title, :body, :user_id, presence: true
    
  def preview    
    last_char_index = 500
    
    if self.body[0...last_char_index].include?('<code>')
      last_char_index = self.body.index('<code>')
    end
    
    if self.body[0...last_char_index].include?('<blockquote>')
      last_char_index = self.body.index('<blockquote>')
    end
    
    "#{self.body[0...last_char_index]}... 
    <br><br>
    <a class='read-more' href='/posts/#{self.id}'>
      Read more
    </a>".html_safe
  end
  
  def display
    highlighted_body.html_safe
  end
  
  def highlighted_body
    code_sections = self.body.scan(/(?<=<code>)[\s\S.]*?(?=<\/code>)/)

    highlighted_code = code_sections.each_with_object([]) do |section, array|
      array << CodeRay.scan(section.strip, :ruby).div(line_numbers: :table)
    end

    highlighted_body = self.body.dup
    code_sections.each_with_index do |section, index|
      highlighted_body.gsub!(section, highlighted_code[index])
    end

    highlighted_body
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    (user && user.is_password?(password)) ? user : nil
  end
  
  attr_reader :password
  after_initialize :ensure_session_token
  
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    save!
    self.session_token
  end
  
  private
  
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :signed_in?, :current_user
  
  def sign_in!(user)
    session[:token] = user.reset_session_token!
    @current_user = user
  end
  
  def sign_out!
    current_user.reset_session_token!
    session[:token] = nil
    @current_user = nil
  end
  
  def signed_in?
    !!current_user
  end
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:token])
  end
  
  def require_signed_in!
    redirect_to root_url unless signed_in?
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_signed_in!, except: [:index, :show, :search]
  
  def index
    @posts = Post.page(params[:page]).per(5)
    render :index
  end
  
  def show
    @post = Post.find(params[:id])
    render :show
  end
  
  def new
    @post = Post.new
    render :new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      redirect_to posts_url
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    render :edit
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url
  end
  
  def search
    @query = params[:query]
    @posts = Post.search_title_and_body(@query).page(params[:page]).per(5)
    render :search
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    
    if @user.nil?
      flash.now[:errors] = ['Invalid email/password combination']
      render :new
    else
      sign_in!(@user)
      redirect_to root_url
    end
  end
  
  def destroy
    sign_out!
    redirect_to new_session_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    render :home
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def authenticity_token
    <<-HTML.html_safe
      <input type='hidden' 
        name='authenticity_token' 
        value="#{form_authenticity_token}">
    HTML
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<ul class='flash errors-list'>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  <img src="<%= asset_url('skyline.png') %>">
</footer>

app/views/layouts/_header.html.erb
<header class="site-header">
  <nav class="clear-fix">
    <div class="logo"><a href="<%= root_url %>">Stefan Huynh</a></div>
    <ul class="clear-fix">
      <li><a href="/#about">About</a></li>
      <li><a href="/#projects">Projects</a></li>
      <li><a href="/#contact">Contact</a></li>
      <li><a href="<%= posts_url %>">Blog</a></li>
    </ul>
  </nav>
</header>

app/views/layouts/_logged_in_header.html.erb
<header class='logged-in-header clear-fix'>
  <nav>
    <form action='<%= session_url %>' method='POST'>
      <input type='hidden' name='_method' value='DELETE'>
      <%= authenticity_token %>
      <button>Log out</button>
    </form>
  
    <a href='<%= new_post_url %>'>New post</a>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stefan Huynh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>
<body>
  
  <main class='site-main'>
    <%= render partial: 'layouts/logged_in_header' if signed_in? %>
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/errors' if flash[:errors] %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </main>
  
  <script>
    $(document).ready(function() {
      $('.intro-section-content').fadeTo(1000, 1);
      
      $('#email-icon').on('click', function(event) {
        event.preventDefault();
        $('.email-modal').removeClass('display-off').fadeTo(200, 1);
      });
  
      $('.close-modal').on('click', function(event) {
        $('.email-modal').fadeTo(200, 0, function() {
          $('.email-modal').addClass('display-off')
        });
      });
      
      // Code snippt from CSS tricks
      $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
          if (location.pathname.replace(/^\//,'') == 
            this.pathname.replace(/^\//,'') && 
            location.hostname == this.hostname) {
              
            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
            if (target.length) {
              $('html,body').animate({
                scrollTop: target.offset().top
              }, 500);
              return false;
            }
          }
        });
      });
    });
  </script>
  
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-54709608-1', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>

app/views/posts/_fields.html.erb
<%= authenticity_token %>

<label for="post-title-field">Title:</label>
<input id="post-title-field"
  type="text"
  name="post[title]"
  value="<%= @post.title %>">
<br>  
<textarea class="post-body-field" name="post[body]"><%= @post.body %></textarea>
<br>

app/views/posts/edit.html.erb
<section class="new-post-section">
  <header class="section-header">
    <h1>Edit Post</h1>
    <hr class="heading-hr">
  </header>
  
  <main>
    <form class="post-form" action="<%= post_url(@post) %>" method="POST">
      <input type='hidden' name='_method' value='PATCH'>
      <%= render partial: 'posts/fields' %>
      <button class="wide-button">Update</button>
    </form>
    
    <form action='<%= post_url(@post) %>' method='POST'>
      <input type='hidden' name='_method' value='DELETE'>
      <%= authenticity_token %>
      <button class="dangerous-button">Delete post</button>
    </form>
  </main>
</section>

app/views/posts/index.html.erb
<section class="blog-section">
  <header class="blog-header">
    <h1>{ Life of Stefan }</h1>
    <hr class="heading-hr">
    <p>Where I blog about code and other things I'm interested in</p>
  </header>
  
  <main class="blog-main clear-fix">
    <section class="left-section">      
      <ul class="posts-list">
        <% @posts.each do |post| %>
          <li class="post-preview">
            <a href='<%= post_url(post) %>'><h2><%= post.title %></h2></a>
            <br>
            <small><%= post.created_at.to_formatted_s(:long_ordinal) %></small>
            <br><br>
            <%= post.preview %>
          </li>
        <% end %>
      </ul>
      <br><br>
      <%= paginate @posts, inner_window: 1 %>
    </section>
  
    <section class="right-section">
      <h3>Search:</h3>
      <form action="<%= search_posts_url %>" method="GET">
        <%= authenticity_token %>
        <input class="search-bar" 
          type="search" 
          name="query" 
          placeholder="What are you looking for?">
      </form>
    </section>
  </main>
</section>

app/views/posts/new.html.erb
<section class="new-post-section">
  <header class="section-header">
    <h1>New Post</h1>
    <hr class="heading-hr">
  </header>
  
  <main>
    <form class="post-form" action="<%= posts_url %>" method="POST">
      <%= render partial: 'posts/fields' %>
      <button class="wide-button">Publish</button>
    </form>
  </main>
</section>

app/views/posts/search.html.erb
<section class="search-section">
  <header class="section-header">
    <h2>Results for:</h2>
    <hr class="heading-hr">
    <h4><%= @query %></h4>
  </header>
  
  <ul class="posts-list">
    <% @posts.each do |post| %>
      <li class="post-preview">
        <a href='<%= post_url(post) %>'><h2><%= post.title %></h2></a>
        <br>
        <small><%= post.created_at.to_formatted_s(:long_ordinal) %></small>
        <p><%= post.preview %></p>
      </li>
    <% end %>
  </ul>
  
  <%= paginate @posts, inner_window: 1 %>
</section>

app/views/posts/show.html.erb
<section class="show-post-section">
  <header class="section-header">
    <h1><%= @post.title %></h1>
    <hr class="heading-hr">
    <p><%= @post.created_at.to_formatted_s(:long_ordinal) %></p>
  </header>

  <main class="show-post-main">
    <p><%= @post.display %></p>
    <br>
    <% if signed_in? %>
      <a href="<%= edit_post_url(@post) %>">Edit</a><br>
    <% end %>
    <a href="<%= posts_url %>">&laquo; All Posts</a>
  </main>
</section>

app/views/static_pages/home.html.erb
<section class="intro-section">
  <div class="intro-section-content">
    <div class="profile-info">
      <div class="profile-text">
        <h1>Hi, my name is Stefan.</h1>
        <h3>
          I am a software engineer with a background in statistics and
          psychology. I work primarily with Javascript and Ruby.
        </h3>
      </div>
    </div>

    <ul class="icon-bar clear-fix">
      <li>
        <a href="http://linkedin.com/pub/stefan-huynh/82/513/8a3/">
          <img src="<%= asset_url('linkedin.png') %>">
        </a>
      </li>
      <li>
        <a href="http://github.com/stefvhuynh">
          <img src="<%= asset_url('github.png') %>">
        </a>
      </li>
      <li>
        <a href="http://twitter.com/stefan_huynh">
          <img src="<%= asset_url('twitter.png') %>">
        </a>
      </li>
    </ul>

    <hr class="heading-hr">
    <h3>huynh.stefan@gmail.com</h3>
  </div>
</section>

<a name="about"></a>
<section class="about-section">
  <header class="section-header">
    <h1>About</h1>
    <hr class="heading-hr">
  </header>

  <main class="about-main">
    <img class="profile-pic" src="<%= asset_url('profile-photo.jpg') %>">
    <p class="about-info">
      I was born and raised in Salt Lake City, UT. I earned my bachelors of
      science in mathematics/statistics and psychology at the University of Utah
      in 2012. I then went to New York University and received my masters in
      experimental psychology in 2014. I currently work as a software engineer
      at Birchbox where I develop in React, Rails, and Magento.
    </p>
    <br><br>
    <hr class="heading-hr"><br>
    <p>
      Check out my resume <a href="<%= asset_url('resume.pdf') %>">here</a>.
    </p>
  </main>
</section>

<a name="projects"></a>
<section class="projects-section">
  <header class="section-header">
    <h1>Projects</h1>
    <hr class="heading-hr">
  </header>
  
  <main class="projects-main">
    <ul class="projects-list clear-fix">
      
      <li class="project">
        <img src="<%= asset_url('twitter-clone.png') %>">
        <div class="project-info-container">
          <div class="project-info">
            <h4>Twitter Clone</h4>
            <p>
              A clone of Twitter. Users can post tweets; follow other 
              users; mention other users and hashtags; search for people, 
              tweets, and hashtags; and more.
            </p>
            <hr class="heading-hr">
            <a href="http://twitter-clone.stefanhuynh.com">Live site</a><br>
            <a href="http://github.com/stefvhuynh/twitter_clone">
              Github repo
            </a>
          </div>
        </div>
      </li>
      
      <li class="project">
        <img src="<%= asset_url('trello-clone.png') %>">
        <div class="project-info-container">
          <div class="project-info">
            <h4>Trello Clone</h4>
            <p>
              A clone of Trello, an organization app. Users can add boards, 
              lists, cards, checklists, and checklist items to keep track of
              projects. Every element can be reordered by dragging and dropping.
            </p>
            <hr class="heading-hr">
            <a href="http://trello-clone.stefanhuynh.com">Live site</a><br>
            <a href="http://github.com/stefvhuynh/trello_clone">
              Github repo
            </a>
          </div>
        </div>
      </li>
      
      <li class="project">
        <img src="<%= asset_url('personal-site.png') %>">
        <div class="project-info-container">
          <div class="project-info">
            <h4>This Site</h4>
            <p>
              A landing page and blog. I made a project of this site by
              writing a Rails app from scratch. I can add blog posts via a
              user interface and visitors can search through all my posts.
            </p>
            <hr class="heading-hr">
            <a href="/posts">Live site</a><br>
            <a href="http://github.com/stefvhuynh/personal_site">
              Github repo
            </a>
          </div>
        </div>
      </li>
      
      <li class="project">
        <img src="<%= asset_url('asteroids.png') %>">
        <div class="project-info-container">
          <div class="project-info">
            <h4>Asteroids</h4>
            <p>
              A pure JavaScript implementation of Asteroids using canvas. Users 
              can fly around (arrow keys) and shoot (spacebar). The asteroids 
              are randomly generated so every one is unique.
            </p>
            <hr class="heading-hr">
            <a href="http://asteroids.stefanhuynh.com">Live site</a><br>
            <a href="http://github.com/stefvhuynh/asteroids">Github repo</a>
          </div>
        </div>
      </li>
      
      <li class="project">
        <img src="<%= asset_url('snake.png') %>">
        <div class="project-info-container">
          <div class="project-info">
            <h4>Snake</h4>
            <p>
              A pure JavaScript implementation of Snake. Users can move around
              and eat apples with the arrow keys.
            </p>
            <hr class="heading-hr">
            <a href="http://snake.stefanhuynh.com">Live site</a><br>
            <a href="http://github.com/stefvhuynh/snake">Github repo</a>
          </div>
        </div>
      </li>
      
      <li class="project">
        <img src="<%= asset_url('rails-lite.png') %>">
        <div class="project-info-container">
          <div class="project-info">
            <h4>Rails Lite</h4>
            <p>
              A lite rebuild of Rails. It includes the controller base, params,
              the router, and session cookies.
            </p>
            <hr class="heading-hr">
            <a href="http://github.com/stefvhuynh/rails_lite">Github repo</a>
          </div>
        </div>
      </li>
      
      <li class="project">
        <img src="<%= asset_url('active-record-lite.png') %>">
        <div class="project-info-container">
          <div class="project-info">
            <h4>Active Record Lite</h4>
            <p>
              A lite rebuild of Active Record. It generates Ruby models from
              SQL queries and builds belongs-to, has-many, and has-many-through
              associations.
            </p>
            <hr class="heading-hr">
            <a href="http://github.com/stefvhuynh/active_record_lite">
              Github repo
            </a>
          </div>
        </div>
      </li>
      
      <li class="project">
        <img src="<%= asset_url('chess.png') %>">
        <div class="project-info-container">
          <div class="project-info">
            <h4>Chess</h4>
            <p>
              A command line implementation of Chess in Ruby. Users can
              take turns playing by specifying the start and end board
              positions.
            </p>
            <hr class="heading-hr">
            <a href="http://github.com/stefvhuynh/chess">Github repo</a>
          </div>
        </div>
      </li>
    </ul>
    
    <hr class="heading-hr"><br><br>
    <h5>See my other projects on my 
      <a href="http://github.com/stefvhuynh"> Github page</a>.
    </h5>
  </main>
</section>

<a name="contact"></a>
<section class="contact-section">
  <header class="section-header">
    <h1>Contact</h1>
    <hr class="heading-hr">
    <h5>Here's how you can get in touch with me.</h5>
  </header>
  
  <main class="contact-main">
    <ul class="icon-bar clear-fix">
      <li>
        <span id="email-icon">
          <img src="<%= asset_url('email.png') %>">
          <p>Email</p>
        </span>
      </li>
      <li>
        <a href="http://linkedin.com/pub/stefan-huynh/82/513/8a3/">
          <img src="<%= asset_url('linkedin2.png') %>">
          <p>LinkedIn</p>
        </a>
      </li>
      <li>
        <a href="http://twitter.com/stefan_huynh">
          <img src="<%= asset_url('twitter2.png') %>">
          <p>Twitter</p>
        </a>
      </li>
    </ul>
  </main>
  
    <div class="email-modal display-off">
      <div class="content">
        <span class="exit close-modal">&times;</span>
        <div class="email-container">
          <h5>huynh.stefan@gmail.com</h5>
        </div>
      </div>
  
      <div class="modal-overlay close-modal"></div>
    </div>
</section>